trigger:
- main

pool:
  name: WindowsAgentPool

steps:
# ✅ 1. Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

# ✅ 2. Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# ✅ 3. Run Sentiment Analysis
- script: |
    python analyze_sentiment.py
  displayName: 'Run Sentiment Analysis Script'

# ✅ 4. Optional (Simulated): Launch Power BI Only if pipeline succeeded
- script: |
    echo ✅ Pipeline succeeded. Opening Power BI Dashboard...
    start "" "C:\Path\To\sentiment_dashboard.pbix"
  condition: succeeded()
  displayName: 'Open Power BI (Only if succeeded)'
