# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: WindowsAgentPool

steps:
- script: echo ✅ Starting Sentiment Analysis Pipeline...
  displayName: 'Step 1: Begin'

- script: |
    echo ✅ Installing dependencies...
    pip install -r requirements.txt

    echo ✅ Running scrape_reviews.py...
    python scrape_reviews.py

    echo ✅ Running analyze_sentiment.py...
    python analyze_sentiment.py

    echo ✅ Done! Output saved to data/sentiment_results.csv
  displayName: 'Step 2: Run Full Pipeline'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'data/sentiment_results.csv'
    artifactName: 'SentimentResults'
    publishLocation: 'Container'
  displayName: 'Step 3: Upload Sentiment Results CSV'

