# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  name: WindowsAgentPool

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python scrape_reviews.py
  displayName: 'Scrape Reviews'

- script: python analyze_sentiment.py
  displayName: 'Analyze Sentiment'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'data/sentiment_results.csv'
    artifactName: 'SentimentOutput'
    publishLocation: 'Container'
