trigger:
- main

pool:
  name: WindowsAgentPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo ✅ Installing Python packages...
    pip install -r requirements.txt

    echo ✅ Running scrape_reviews.py...
    python scrape_reviews.py

    echo ✅ Running analyze_sentiment.py...
    python analyze_sentiment.py

    echo ✅ Done! Output saved to data/sentiment_results.csv
  displayName: 'Run Sentiment Analysis Pipeline'
